/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import pilgrimscrutinizer.DBOperation;
import pilgrimscrutinizer.Dailypayments;
import pilgrimscrutinizer.Paymentdetails;
import pilgrimscrutinizer.Tourtable;
import pilgrimscrutinizer.customerdetails;
import pilgrimscrutinizer.tourdetails;

/**
 *
 * @author HP
 */
public class ReversePayment extends javax.swing.JFrame {

    private String user;
    ArrayList<Paymentdetails> plist;
    DBOperation dbo = new DBOperation();

    /**
     * Creates new form ReversePayment
     */
    public ReversePayment() {
        initComponents();
        txtno.setVisible(false);
        loadTable();
        System.out.print("jjjj");
        btnprint.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void loadTable() {
        plist = dbo.getdailypayments();
        if (plist == null) {
            JOptionPane.showMessageDialog(this, "Network error, Try Again..!");
            txtno.setVisible(true);
        } else if (plist.isEmpty()) {
            txtno.setVisible(true);
        } else {
            Dailypayments dp = new Dailypayments(plist);
            tblpayments.setModel(dp);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtno = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpayments = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnreverse = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select to Reverse", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        txtno.setEditable(false);
        txtno.setBackground(new java.awt.Color(255, 51, 51));
        txtno.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtno.setForeground(new java.awt.Color(0, 204, 0));
        txtno.setText("No Transactions for Today...!");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tblpayments.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        tblpayments.setForeground(new java.awt.Color(255, 0, 0));
        tblpayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblpayments);

        btnView.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnreverse.setBackground(new java.awt.Color(255, 255, 153));
        btnreverse.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnreverse.setForeground(new java.awt.Color(255, 0, 0));
        btnreverse.setText("Reverse ");
        btnreverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreverseActionPerformed(evt);
            }
        });

        btncancel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnprint.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnprint.setText("Re-Print");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreverse, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(btnprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(102, 102, 102))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnreverse, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        try {
            Paymentdetails pyd = plist.get(tblpayments.getSelectedRow());
            tourdetails td = dbo.viewTourDetails(pyd.getTourId());
            customerdetails csd = dbo.Viewcustomer(pyd.getCustId());
            JOptionPane.showMessageDialog(this, "Name: "+csd.getName()+ "\n" +"NIC: "+csd.getNicno()+ "\n" +"Tour: " + td.getTourname() + "\n" + "Destination: " + td.getDestination() + "\n" + "Date: " + td.getDate());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Please select a Payment...! ");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnreverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreverseActionPerformed
        // TODO add your handling code here:
        try {
            int response = JOptionPane.showConfirmDialog(this, "Are you realy want to reverse this payment?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_NO_OPTION){
            Paymentdetails pyd = plist.get(tblpayments.getSelectedRow());
            tourdetails td = dbo.viewTourDetails(pyd.getTourId());
            customerdetails csd = dbo.Viewcustomer(pyd.getCustId());
            Tourtable tt = dbo.viewtourtable(td.getTourid(), csd.getCustid());
            double newoutsd = tt.getTotalpaid() - pyd.getAmount();
            System.out.println(newoutsd);
            if (pyd.getAmount() < 0) {
                JOptionPane.showMessageDialog(this, "Can't reverse Again..!");
            } else {
                boolean ttble = dbo.paymenttour(csd.getCustid(), td.getTourid(), newoutsd);
                if (ttble) {
                    Paymentdetails pd = new Paymentdetails();
                    pd.setCustId(pyd.getCustId());
                    pd.setTourId(pyd.getTourId());
                    pd.setUsername(user);
                    pd.setAmount(-(pyd.getAmount()));
                    boolean rvsptble = dbo.setpaymenttable(pd);
                    if (rvsptble) {
                        JOptionPane.showMessageDialog(this, "RS:" + pyd.getAmount() + "/- " + "Reversed Successfully");
                        btnreverse.setEnabled(false);
                        btnprint.setVisible(true);
                        loadTable();
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Network error try again..!");

                }
            }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Please select a Payment...! ");
        }
    }//GEN-LAST:event_btnreverseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReversePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReversePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReversePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReversePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReversePayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnreverse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblpayments;
    private javax.swing.JTextField txtno;
    // End of variables declaration//GEN-END:variables

    /**
     * @param user the user to set
     */
    public void setUser(String user) {
        this.user = user;
    }
}
